#!/usr/bin/env bash

set -o errexit

npm run build
binary=./bin/elm-typescript-interop

for testFolder in ./test_data/*
do
  echo "Testing generator with $testFolder folder"
  outputBase=`basename $testFolder`
  outputPath=tests/e2e/output/$outputBase.d.ts
  $binary $testFolder/*.elm --output $outputPath
  echo "Checking that $outputPath is a valid typescript declaration file..."
  tsc $outputPath
done

# echo 'Ensuring documentation is valid...'
# elm make --docs=documentation.json

echo 'Confirming that generated code is unchanged...'
git diff --exit-code -- tests/e2e/output || (echo 'FAILURE' && echo 'examples code has changed. Commit changes to approve.' && exit 1)


# npm run approve-compilation

echo 'SUCCESS'
